### ISSUE TITLE
Criar .gitignore e remover arquivos de ambiente

### ISSUE THREAD

**Issue by jacksoncl7** [gustavoanalise/flaskIntroduction#1]
1. Criar arquivo de .gitignore, [doc](https://git-scm.com/docs/gitignore).
   * inserir nesse arquivo o diretórios `venv` e `__pycache__`.
   
2. Remover `venv` e `__pycache__` do repositório Git.
   * vc precisa desses arquivos na sua máquina as outras pessoas não.
   * se vc simplesmente excluir pode ser que o projeto pare de funcionar na sua máquina.
   * É necessário remover o arquivos do "tracking" do git, ao invés de excluílos. Pesquise como se faz isso.
 
 A tarefa está ordenada na ordem que eu acredito que será mais fácil pra vc executar.

**Comment by gustavoanalise** [comment]
It's done.
